# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='forms',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
